"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import AdminShell from "@/components/AdminShell";
import {supabase} from "@/lib/supabase";

type N={id:number;name:string;slug:string;summary:string|null;description:string|null;image_url:string|null;gallery_urls:string[]|null;map_url:string|null;population:string|null;altitude:string|null;area_size:string|null;transportation:string|null;infrastructure:string|null;zoning_note:string|null;seo_title:string|null;seo_description:string|null;is_active:boolean;sort_order:number};
type F={id:number;name:string;slug:string;summary:string;description:string;image_url:string;gallery_text:string;map_url:string;population:string;altitude:string;area_size:string;transportation:string;infrastructure:string;zoning_note:string;seo_title:string;seo_description:string;is_active:boolean;sort_order:number};
const empty:F={id:0,name:"",slug:"",summary:"",description:"",image_url:"",gallery_text:"",map_url:"",population:"",altitude:"",area_size:"",transportation:"",infrastructure:"",zoning_note:"",seo_title:"",seo_description:"",is_active:true,sort_order:0};
const slugify=(v:string)=>v.toLocaleLowerCase("tr-TR").replaceAll("ç","c").replaceAll("ğ","g").replaceAll("ı","i").replaceAll("ö","o").replaceAll("ş","s").replaceAll("ü","u").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");
const txt=(v:string)=>v.trim()||null;
const gallery=(v:string)=>{const a=v.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);return a.length?a:null};

export default function Page(){
 const [items,setItems]=useState<N[]>([]),[form,setForm]=useState<F>(empty),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);const r=await supabase().from("neighborhoods").select("*").order("sort_order").order("name");if(r.error)setError(r.error.message);else setItems((r.data??[]) as N[]);setLoading(false)}
 const set=<K extends keyof F>(k:K,v:F[K])=>setForm(p=>({...p,[k]:v}));
 function edit(i:N){setForm({id:i.id,name:i.name,slug:i.slug,summary:i.summary??"",description:i.description??"",image_url:i.image_url??"",gallery_text:(i.gallery_urls??[]).join("\n"),map_url:i.map_url??"",population:i.population??"",altitude:i.altitude??"",area_size:i.area_size??"",transportation:i.transportation??"",infrastructure:i.infrastructure??"",zoning_note:i.zoning_note??"",seo_title:i.seo_title??"",seo_description:i.seo_description??"",is_active:i.is_active,sort_order:i.sort_order});window.scrollTo({top:0,behavior:"smooth"})}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");setError("");const p={name:form.name.trim(),slug:slugify(form.slug||form.name),summary:txt(form.summary),description:txt(form.description),image_url:txt(form.image_url),gallery_urls:gallery(form.gallery_text),map_url:txt(form.map_url),population:txt(form.population),altitude:txt(form.altitude),area_size:txt(form.area_size),transportation:txt(form.transportation),infrastructure:txt(form.infrastructure),zoning_note:txt(form.zoning_note),seo_title:txt(form.seo_title),seo_description:txt(form.seo_description),is_active:form.is_active,sort_order:Number(form.sort_order)||0,updated_at:new Date().toISOString()};const q=form.id?supabase().from("neighborhoods").update(p).eq("id",form.id):supabase().from("neighborhoods").insert(p);const r=await q;if(r.error)setError(r.error.message);else{setMessage("Mahalle kaydedildi.");setForm(empty);await load()}setSaving(false)}
 async function del(i:N){if(!confirm(`${i.name} silinsin mi?`))return;const r=await supabase().from("neighborhoods").delete().eq("id",i.id);if(r.error)setError(r.error.message);else{setMessage("Mahalle silindi.");await load()}}
 async function toggle(i:N){await supabase().from("neighborhoods").update({is_active:!i.is_active}).eq("id",i.id);await load()}
 const filtered=useMemo(()=>{const q=search.toLocaleLowerCase("tr-TR");return items.filter(i=>`${i.name} ${i.summary??""}`.toLocaleLowerCase("tr-TR").includes(q))},[items,search]);
 return <AdminShell>
  <header className="admin-topbar"><div><p className="admin-eyebrow">V3 YAYIN SÜRÜMÜ</p><h1>Mahalleler</h1><p>Mahalle içerikleri ve fotoğraf galerisi.</p></div><span className="admin-status">{items.length} Mahalle</span></header>
  {message&&<div className="note ok">{message}</div>}{error&&<div className="note bad">{error}</div>}
  <section className="admin-panel"><h2>{form.id?`${form.name} mahallesini düzenle`:"Yeni mahalle ekle"}</h2>
   <form onSubmit={save}><div className="grid">
    <label>Mahalle Adı<input value={form.name} onChange={e=>{set("name",e.target.value);if(!form.id)set("slug",slugify(e.target.value))}} required/></label>
    <label>Sayfa Adresi<input value={form.slug} onChange={e=>set("slug",slugify(e.target.value))} required/></label>
    <label>Sıralama<input type="number" value={form.sort_order} onChange={e=>set("sort_order",Number(e.target.value))}/></label>
    <label>Yayın Durumu<select value={form.is_active?"1":"0"} onChange={e=>set("is_active",e.target.value==="1")}><option value="1">Yayında</option><option value="0">Yayın Dışı</option></select></label>
    <label className="full">Kısa Tanıtım<textarea rows={3} value={form.summary} onChange={e=>set("summary",e.target.value)}/></label>
    <label className="full">Uzun Açıklama<textarea rows={6} value={form.description} onChange={e=>set("description",e.target.value)}/></label>
    <label className="full">Kapak Fotoğrafı URL<input value={form.image_url} onChange={e=>set("image_url",e.target.value)}/></label>
    <label className="full">Galeri Fotoğrafları<textarea rows={7} value={form.gallery_text} onChange={e=>set("gallery_text",e.target.value)} placeholder={'Her satıra bir URL yazın\nhttps://.../foto1.jpg\nhttps://.../foto2.jpg'}/><small>Her satıra bir fotoğraf bağlantısı.</small></label>
    <label className="full">Google Harita Embed URL<input value={form.map_url} onChange={e=>set("map_url",e.target.value)}/></label>
    <label>Nüfus<input value={form.population} onChange={e=>set("population",e.target.value)}/></label><label>Rakım<input value={form.altitude} onChange={e=>set("altitude",e.target.value)}/></label><label>Yüzölçümü<input value={form.area_size} onChange={e=>set("area_size",e.target.value)}/></label><label>Ulaşım<input value={form.transportation} onChange={e=>set("transportation",e.target.value)}/></label>
    <label className="full">Altyapı<textarea rows={3} value={form.infrastructure} onChange={e=>set("infrastructure",e.target.value)}/></label><label className="full">İmar ve Tapu Notu<textarea rows={3} value={form.zoning_note} onChange={e=>set("zoning_note",e.target.value)}/></label><label className="full">SEO Başlığı<input value={form.seo_title} onChange={e=>set("seo_title",e.target.value)}/></label><label className="full">SEO Açıklaması<textarea rows={3} value={form.seo_description} onChange={e=>set("seo_description",e.target.value)}/></label>
   </div><div className="buttons">{form.id!==0&&<button type="button" className="secondary" onClick={()=>setForm(empty)}>İptal</button>}<button className="primary" disabled={saving}>{saving?"Kaydediliyor...":"Kaydet"}</button></div></form>
  </section>
  <section className="admin-panel list"><div className="head"><h2>Kayıtlı mahalleler</h2><input placeholder="Mahalle ara..." value={search} onChange={e=>setSearch(e.target.value)}/></div>{loading?<p>Yükleniyor...</p>:<table><thead><tr><th>Mahalle</th><th>Galeri</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{filtered.map(i=><tr key={i.id}><td><strong>{i.name}</strong><small>{i.summary||"Tanıtım yok"}</small></td><td>{i.gallery_urls?.length??0} fotoğraf</td><td><button className={i.is_active?"status on":"status off"} onClick={()=>void toggle(i)}>{i.is_active?"Yayında":"Yayın Dışı"}</button></td><td><button className="edit" onClick={()=>edit(i)}>Düzenle</button> <button className="delete" onClick={()=>void del(i)}>Sil</button></td></tr>)}</tbody></table>}</section>
  <style jsx>{`.note{padding:14px;margin-bottom:18px;border-radius:10px}.ok{background:#0d2a24;color:#70e5bd}.bad{background:#35171c;color:#fca5a5}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}label{display:grid;gap:7px}.full{grid-column:1/-1}input,textarea,select{padding:13px;border:1px solid #2a3c59;border-radius:10px;background:#081221;color:white}small{color:#8795aa}.buttons{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.primary,.secondary,.edit,.delete,.status{padding:10px 14px;border-radius:9px;font-weight:800;cursor:pointer}.primary{border:0;background:#f47b20;color:white}.secondary,.edit{border:1px solid #2a3c59;background:#111c2e;color:white}.delete{border:1px solid #713139;background:#33151a;color:#fca5a5}.list{margin-top:18px}.head{display:flex;justify-content:space-between;align-items:center}table{width:100%;border-collapse:collapse}th,td{padding:14px;border-bottom:1px solid #20304a;text-align:left}td strong,td small{display:block}.status.on{background:#0d2a24;color:#38dbac}.status.off{background:#35171c;color:#fca5a5}@media(max-width:760px){.grid{grid-template-columns:1fr}.full{grid-column:auto}.head{align-items:stretch;flex-direction:column;gap:10px}}`}</style>
 </AdminShell>
}
